---
ansible_user: ubuntu
ansible_ssh_private_key_file: ../BastionHostKey.pem


# Use first Web instance as bastion for private App layer
# ansible_ssh_common_args: "-o ProxyJump=ubuntu@{{ hostvars[groups['tag_Tier_Web'][0]].ansible_host }}"