---
# - name: Update APT Cache
#   ansible.builtin.apt:
#     update_cache: yes


- name: Install Python3
  ansible.builtin.apt:
    name: python3
    state: present


- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'


- name: Copy app.py
  ansible.builtin.copy:
    src: app.py
    dest: "{{ app_dir }}/app.py"
    mode: '0755'


- name: Create app service
  ansible.builtin.template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service
    mode: '0644'
    

- name: Check running service
  ansible.builtin.service:
    name: app
    state: started
    enabled: true